### ISSUE TITLE
Bounds checking required for acceptance into .NET Core

### ISSUE THREAD

**Issue by nietras** [damageboy/VxSort#12]
@damageboy I am very impressed with the awesome work you have done with regards to optimizing sorting for ints and not the least the blog posts that look stunning! 

As you might know I proposed the expansion of `Sort` to spans in:

https://github.com/dotnet/runtime/issues/19969

I then continued to spent quite a lot of time implementing `Sort` in 100% managed code with no pinning of memory and with 100% fidelity to existing sort. At performance on par or better. This can be found (there were other PRs but this was the main PR):

https://github.com/dotnet/corefx/pull/26859

Now this was rejected for the use of "bare" `ref`, and as far as I understood doing the sorting without bounds checking e.g. via pointers would not be acceptable. Hence, why I write to you. I don't think that they will accept sorting based on raw pointers due to this. They've seen too many security issues because of this.

Another thing is that I wrote quite a lot of extensive tests incl. benchmarks for the sorting code. This can be found at:

https://github.com/dotnetcross/sorting

Perhaps you can use that for battle testing your code. There are many different scenarios that have different performance profiles. I hope someday to release the above as a nuget package, for all incl. old runtimes.

Later Stephen Toub finished the change to use `Span` and only have managed code in:

https://github.com/dotnet/coreclr/pull/27700

**Comment by nietras** [comment]
Actually this PR reflects the latest version I think of the dotnetcross/sorting stuff:

https://github.com/DotNetCross/Sorting/pull/4

**Comment by damageboy** [comment]
Hi back!

I've been following your work closely, to be honest, regarding the spanification and earlier attempts that were rejected too!

It's so nice of you to have written, both about the code, blog and just for caring.

I really don't know what to expect about the whole PR process.

I'll do a draft PR, and will really limit my-self from doing the whole thing (e.g. more types, and more code).

To be honest, I fully expect it to be rejected from CoreCLR on multiple grouds, starting with all the reasons you mentioned and also due to complexity and code size.

Anyway, I would love to do it with Spans and bounds checking, except that intrinsics themselves to no support this.

I do have hand-rolled bounds checking in my research branch, and I even posted a really short blog post on how I [hijack local functions wirh `#if DEBUG` to achieve this](https://bits.houmus.org/2019-11-08/unsafe-bounds-checking), but I suspect this is not acceptable as a solution (and would also cause huge perf degradation anyway).

Anyway, I think my expectations are very realistic about this:)
In part this is the reason I created this repo, accpeting my fate as it were.
Hopefully doing 10x sorting, and when, eventually AVX512 makes its way to more computers and CoreCLR we will get a 30x-ish (my guess) improvemnet.

**Comment by redknightlois** [comment]
That is the reason I believe that first order of business should be to release power-sort (I just created a name for it) into nuget. 10x improvement is too big to anyone with reasonable sorting requirements to pass. It could easily become the de-facto sort, under that light there would be no reason why not to at least include `Unsafe.Sort` as an alternative implementation.

**Comment by nietras** [comment]
> I would love to do it with Spans and bounds checking, except that intrinsics themselves to no support this.

@damageboy right, but you can still do something like:
```csharp
Span<Vector256> vectorSpan = MemoryMarshal.Cast<int, Vector256>(intSpan);
```
where you of course have to ensure proper size etc. There will be quite a bit of overhead, you can only read "unaligned" etc. In fact alignment is an issue. But you are probably aware of that :)

> I hijack local functions wirh #if DEBUG to achieve this, but I suspect this is not acceptable as a solution

I really liked that hack :+1: But I wouldn't think so either, but who knows.

> 10x sorting, and when, eventually AVX512 makes its way to more computers and CoreCLR we will get a 30x-ish (my guess) improvemnet

Definitely, AVX512 support is on my wish list too. :)

> into nuget. 

I second that nuget package with this in it, would be interesting for a lot of users. It doesn't have to be in coreclr.

**Comment by Genbox** [comment]
I just want to chime in here and say good job to both @nietras and @damageboy. Thank you both for looking into improving the fundamentals of the .NET framework.

If something is marshalled away to native land, it should be just as good to have it in unmanaged C#. I honestly think that some things such as sorting, random generators, hash functions etc. should be implemented in SIMD and the JIT should make a decision on which implementation can be used.
